name: Build
on:
    pull_request:
    push:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Install
              run: yarn install --frozen-lockfile
            - name: Build
              run: yarn build