name: Build and Commit

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensure full history for commit

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run build
        run: yarn build

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b build-update-${{ github.run_id }}
          git add -f build  # Force add build folder
          git commit -m "chore: update build output [CI skip]" || exit 0
          git push origin build-update-${{ github.run_id }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: build-update-${{ github.run_id }}
          title: "chore: update build output"
          body: "This PR updates the build output after the latest commit to main."
          base: main
          labels: "automerge"
